### PR TITLE
Styling/labels

### LINKED ISSUE #107: Add missing form labels per WAVE accessibility audit

### PR DESCRIPTION
**Pull request by tashiad**
### What Type of PR Is This?
- [ ] New Feature 
- [x] Bug Fix
- [ ] Testing
- [ ] Refactoring/Clean Up 

#### What does this branch do? 
* Resolves WAVE errors, mostly due to missing form labels
* Miscellaneous styling fixes

Note: While this solved the majority of errors and warnings in WAVE, there are 2 remaining that I wasn't sure how to go about fixing.

The first is that the labels for the text areas need to be unique, but since the `TextField` component is reusable, I'm unable to add unique labels to it. I tried making It come from either the value or the prompt props, but that doesn't work if the value is missing. and it threw errors for the prompt prop type.

The second issue is that `<input type="submit" className="button-submit" />` is an "empty button" so we might need to break the `onSubmit` function out further and turn it into an actual button with text.

Since both of these issues would require significant refactoring in order to fix them (I think--unless someone knows of an easier way!), I left for now to come back to later.

#### Have you tested your branch? How?
Chrome/dev tools

#### Do all existing unit and integration tests pass? 
N/A

#### Does this branch require special installation steps? 
N/A

#### Related Issues:
Closes #107

### CODE REVIEW

**Review by deadbelly — CHANGES_REQUESTED** [review]
I don't have any specific comments on code, it all looks great to me, but I'm wondering a potential way to fix the issue with text area labels. Right now each text area has a unique `prompt` string, could we just make that the label?

**Comment by tashiad** [comment]
@deadbelly so I tried having it be the `prompt` string but you get this TS error:
Screen Shot 2021-05-05 at 9 35 43 AM

I believe this is because not all `TextFields` have a `prompt` (line 190 of `TourForm`)

**Comment by deadbelly** [comment]
So looking at the multiform I'm pretty sure this error comes when rendering the `DEBRIEF` portion, because those fields do not have prompts. I think there are three potential solutions:

1. Add prompts to the debrief fields, maybe use some text from the book.
2. Add a third argument to `renderTextFields` in `TourForm`. This argument could be called `labels` and would be an array of strings. When we map over `fields` we grab `labels[i]` and add it as a hidden label.
3. Decide we're good with our current accessibility options since screen readers will likely read the H3 before getting to the text box anyways. 

Side note: I think we might be able to pass the check just by adding a `name` attribute to each text field instead of a `label` element but I'm not 100% sure.

**Comment by tashiad** [comment]
I'll try just adding prompts to the Debrief fields. There aren't any in the book but I can make them up.

Thoughts on the "empty button"? Is there a reason you made it into an `<input>` rather than a `<button>` or can I change it?

**Comment by deadbelly** [comment]
I'm trying to remember why we did that. It might have been so that you can submit the form by hitting enter, which is maybe not necessary anymore? I think we should convert to a button and see if it causes any significant problems. My guess is it won't.

**Review by deadbelly — APPROVED** [review]
Awesome this looks great! Thanks for working through those changes and that CI weirdness.

**Pull request merged**
